# Site settings
name: Andersen Lab
title: Andersen Lab
email: lab@andersenlab.org
description: "The Andersen Lab @ Northwestern"
baseurl: ""
url: "http://www.andersenlab.org"
permalink: /:categories/:title.html

# RSS
rss_path: feeds/
rss_name: rss.xml

# Page Set
pages_list:
  About: '/about'
  Feed: '/atom.xml'

# Build settings
permalink: pretty

#exclude
exclude: ["scripts/", "build.sh", "README.md", ".DS_Store", 'assets/less/', 'andersenlabsite.sublime-project', 'andersenlabsite.sublime-workspace']



